name: GitHub Security Report Action
description: Generates security reports for a GitHub repository
author: Peter Murray

inputs:
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

  sarifReportDir:
    description: The CodeQL output directory for SARIF report(s).
    required: false
    default: "../results"

  outputDir:
    description: The output directory for the generated report(s).
    required: false
    default: ${{ github.workspace }}

  repository:
    description: Repository name with owner. For example, peter-murray/github-security-report
    required: false
    default: ${{ github.repository }}

  templateFile:
    description: File to use as PDF template. For example, summary.pdf
    required: false

runs:
  using: node12
  main: dist/index.js

branding:
  icon: shield
  color: green