FROM ghcr.io/octodemo/container-nodejs-development:base-latest

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y libappindicator1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 \
        libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 \
        libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 \
        libxrender1 libxss1 libxtst6 libglib2.0-dev libnss3-dev libxrandr-dev libatk1.0-dev libatk-bridge2.0-dev libx11-xcb-dev \
        libxcb-dri3-dev libxcomposite-dev libxcursor-dev libxdamage-dev libcups2 libdrm-dev libgbm-dev