name: Manual Test Repository

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Invoke Action
        uses: ./
        with:
          token: ${{ secrets.TEST_TOKEN }}
          sarifReportDir: ./samples/sarif/java/detailed
          outputDir: .
          repository: octodemo/ghas-reporting

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./*.pdf
